version: '3.8'
services:
  app:
    build: 
      context: ./app
    restart: unless-stopped
    env_file:
      - ./app/.env
    environment:
      - PORT=${APP_CONTAINER_PORT}
      - DB_HOST_PORT=${DB_HOST_PORT} 
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - ${APP_HOST_PORT}:${APP_CONTAINER_PORT}
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm run dev  
    
  mysqldb:
    image: mysql:lts-oraclelinux9
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - db:/var/lib/mysql
  
